src/BlazorStrap/Modal.cshtml

Fixes Modal not closing when clicking outside of the dialog.

Fixed Modal not closing when clicking outside of the dialog

---

src/BlazorStrap/wwwroot/blazorStrap.js

The wrong component name was used to created computed class resulting in
wrong BS class beign applied to tooltip arrow and transparent
background.
The `hide` is not required, empty `tooltip` class hides the instance as
the opacity is being set to 0.
Thanks!

Fix tooltips arrow color and remove unused class

---

src/BlazorStrap/Components/Forms/BSButton.razor.cs

BSButton type Submit is rendered as an input. Is this intended?

BSBUtton Input Submit changed to Button Submit

---

src/BlazorStrap/Components/BSAlert.razor
src/BlazorStrap/Components/BSToast.Razor
src/BlazorStrap/Components/Layout/BSCollapseToggle.razor
src/BlazorStrap/Components/Model/BSModalHeader.razor

The Bootstrap specific data atributes are not used in detail for Alert,
Toast, Toggle and Modal. They are relevant only when using automated
feaetures of BS components backed by plain JavaScript implementation.
Thanks!

Remove BS specific data attributes from Razor markup.

---

src/BlazorStrap/Components/Forms/BSBasicInput.cs
src/BlazorStrap/Components/Forms/BSInput.cs

Addressing #227 .
Added generation of "max" attribute with a default of "9999-12-31" for date fields.
This will create the default behaviour of the year only allowing 4 digits for the year.
I also updated the attribute sequence numbers around the rendering of MaxDate to ensure no duplicates.
I wasn't able to figure out a way to test this unfortunately :(
It builds fine but couldn't get `Sample`, `SampleCore`, or `ServerSideSample` to run for me.
I also couldn't find any guidelines on testing so let me know if there is a process for it that I missed.

Added MaxDate to BSinput and BSBasicInput

---

src/BlazorStrap/Components/Layout/BSTable.razor.cs

The name of the property is incorrect and does not match the documentation title or the bootstrap class name.

Update BSTable.razor.cs to fix typo for IsHovarable => IsHoverable

---

src/BlazorStrap/Components/BSCustomizer.razor.cs

Add missing:
- font family sans-serif
- font family monospace
Ref:
https://github.com/twbs/bootstrap/blob/master/scss/_root.scss#L13-L14
Thanks!

Sync customizer config with BS CSS3 properties

---

src/BlazorStrap/Components/Model/BSModal.razor
src/BlazorStrap/Components/Model/BSModal.razor.cs
src/SampleCore/Pages/Modals.razor
src/SampleCore/SampleCore.csproj
src/SampleCore/wwwroot/snippets/modals/modals5.html
src/SampleCore/wwwroot/snippets/modals/modals6.html
src/SampleCore/wwwroot/snippets/modals/modals7.html
src/SampleCore/wwwroot/snippets/modals/modals8.html
src/SampleCore/wwwroot/snippets/modals/modals9.html

Added 4 new options on bootstrap modal components. IsFullWidth for a full width modal, IsBottom to place modal at the bottom of the screen, IsFullHeight to place modal on the full height of the screen, IsFullScreen for a full screen window. You can have a bottom sheet like modal using the combined options of IsFullWidth and IsBottom. Modal examples pages have been updated with this changes as well.

Added 4 new options on bootstrap modal component. IsFullWidth, IsBottom, IsFullHeight and IsFullScreen.

---

src/SampleCore/Pages/Tables.razor
src/SampleCore/wwwroot/snippets/tables/tables10.html

Fixed Typo on examples: IsHovarable -> IsHoverable

Fixed typo on example page: IsHovarable -> IsHoverable

---

src/BlazorStrap/Components/ListGroup/BSListGroupItem.razor.cs

Bootstrap href or button on list groups uses the class list-group-item-action which provides actionable feedback to the user.

Added missing class on ListGroupItem -> list-group-item-action when ListGroupType != ListGroupType.List

---

src/BlazorStrap/Components/Model/BSModal.razor.cs
src/BlazorStrap/Util/BlazorStrapInterop.cs
src/BlazorStrap/wwwroot/blazorStrap.js

Fixes #299
JSInterop has option to call instance of method:
https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1#instance-method-call

Fix issue where all modals across devices close when escape is enabled/pressed

---

src/BlazorStrap/Components/Layout/BSCollapse.razor.cs

Fix BSCollapse not actually showing/hiding unless you are subscribed to the ShowEvent (to show) and the HideEvent (to hide)
This code wasn't working:
<BSCollapseItem>
<BSCollapseToggle IsLink="true">Toggle</BSCollapseToggle>
<BSCollapse>
<p>Content</p>
</BSCollapse>
</BSCollapseItem>
This code would work:
<BSCollapseItem>
<BSCollapseToggle IsLink="true">Toggle</BSCollapseToggle>
<BSCollapse ShowEvent="@(() => Console.WriteLine("Show"))" HideEvent="@(() => Console.WriteLine("Hide"))">
<p>Content</p>
</BSCollapse>
</BSCollapseItem>

Fix BSCollapse not actually showing/hiding

---

src/BlazorStrap/Components/Tabs/BSTab.razor.cs

This fixes the exception I reported in 270.
Also found another issue that this fixes. I have a page with 2 tabs where first tab is selected. When I go to another page, it first changes tab and runs Invoke on show method for second tab before navigating to other page.

Fixes #270 tab exception. Also fixes next tab loading when leaving page.

---

src/BlazorStrap.Extensions.DataComponents/Components/BSDataTable/RemoteDataTable.razor
src/BlazorStrap.Extensions.DataComponents/Components/BSDataTable/RemoteDataTable.razor.cs
src/BlazorStrap.Extensions.DataComponents/Components/BSDataTable/RemotePagination.razor
src/BlazorStrap.Extensions.DataComponents/Components/BSDataTable/RemotePagination.razor.cs

**WIP**
Adds the start of a remote data table. Builds off of DataTable (Note: right now it doesn't use the DataTable internally because they might not work the same way once you add sorting and filtering, but if possible similar functionality should be merged).
Right now, only supports pagination, not sorting filtering or any other advanced functionality. It does it by having the user supply the items just like in the regular DataTable, plus page number, total records and per page counts. As well as a UrlPattern (Have to use urls/routing because OnClick of BSPaginationLink is broken #320). Although personally, I prefer url routing when possible as it makes the app more browser friendly, but not everyone will want that.
I did not add documentation yet, but I wanted to get thoughts on this. …

Remote data table

---

src/BlazorStrap.Extensions.FluentValidation/FluentValidation.cs

I have a FluentValidator that requires resolving dependencies via DI.
I am unable to use the current component for FluentValidator as it requires me to pass in the type with a new() constraint, which then just creates the validator, without resolving it.
As changing this would be a breaking change I have added an alternative InjectFluentValidator component which detects the IValidator<> type required based on the EditContext model and injects it.
This requires the validator to be registered in the service collection, eg:
services.AddTransient<IValidator<MyModel>, MyModelValidator>();
Open to discussion if there is a better way of solving this problem?

Alternative FluentValidatorInjected component to use DI to inject a validator

---

src/BlazorStrap/wwwroot/css/cromefix.css
src/SampleCore/Pages/Samples/Issue330.razor

This fix overrides Bootstraps CSS to stop animations when reduced animations is turned on. Instead it sets the animations to last .001ms. This accomplishes the need for reduced animations for those with physical issues such as vestibular disorders while still allowing our events to fire normally.
This PR fixes #330

Fixed bug #330

---

src/BlazorStrap/Components/Forms/BSInput.cs
src/BlazorStrap/Util/TryParseString.cs
src/SampleCore/Pages/Samples/InputTime.razor

I needed a way to handle milliseconds and normal Time from BSInput, but noticed, that it currently isn't working at all, because the format pattern for converting in both directions is only specified for Date.
Additionally I noticed, that BSInput.TryParseDateTime and BSInput.TryParseDateTimeOffset aren't used anywhere in the solution (at least I found nothing). Maybe that should be removed, so it doesn't confuse People (like me :))

Fixed BSInput Type=Time not working

---

src/BlazorStrap/Properties/Resources.Designer.cs
src/BlazorStrap/Util/Components/ColumnBase.cs
src/SampleCore/Pages/Layout.razor
src/SampleCore/Pages/Samples/Issue370.razor

This pull request fixes Issue #370 
Allows setting the following offsets to be set to zero. XSOffset, SMOffset, MDOffset, LGOffset, and XLOffset to be set to zero (0). Also updated documentation to reflect this.

Fix for BSCol for Offset Set to zero

---

docs/_content/SampleCore/snippets/forms/forms12.html
src/SampleCore/Pages/Forms.razor
src/SampleCore/wwwroot/snippets/forms/forms12.html

This is a small PR aligning the documentation with the markup.
**Before:**
**After:**

Eliminate discrepancy between the markup and the docs

---

src/BlazorStrap/Components/Forms/BSBasicInput.cs

Looks like in the recent changes for nullable bools a `||` was used instead of a `&&` which prevent ordinary checkboxes from binding correctly (the bound variable wasn't updating from false).

Tweak to fix checkboxes

---

src/BlazorStrap/Components/Forms/BSInput.cs

#396 was for BSBasicInput, this for BSInput.
Looks like in the recent changes for nullable bools a `||` was used instead of a `&&` which prevent ordinary checkboxes from binding correctly (the bound variable wasn't updating from false).
BSInput reproduction example
```
@page "/"
<h1>Hello, world!</h1>
<div>
<BSForm Model="ViewModel">
<BSFormGroup IsCheck="true">
<BSInput name="test" id="test" InputType="InputType.Checkbox" @bind-Value="ViewModel.Test" />
<BSLabel IsCheck="true" For="test">Click</BSLabel>
</BSFormGroup>
</BSForm>
<div>
@(ViewModel.Test ? "Yes": "No")
</div>
</div>
@code {
private Model ViewModel { get; set; } = new Model();
public class Model
{
public bool Test { get; set; }
}
}
```

Same change as #396 for BSInput

---

BlazorStrap.Tests/BlazorStrap.Tests.csproj
src/BlazorStrap.Extensions.BSDataTable/BlazorStrap.Extensions.BSDataTable.csproj
src/BlazorStrap.Extensions.FluentValidation/BlazorStrap.Extensions.FluentValidation.csproj
src/BlazorStrap.Extensions.SvgLoader/BlazorStrap.Extensions.SvgLoader.csproj
src/BlazorStrap.Extensions.TreeView/BlazorStrap.Extensions.TreeView.csproj
src/BlazorStrap/BlazorStrap.csproj
src/BlazorStrap/Components/Forms/BSForm.cs
src/BlazorStrap/Properties/Resources.Designer.cs
src/BlazorStrap/Properties/Resources.resx
src/Sample/ClientSideSample.csproj
src/SampleCore/SampleCore.csproj
src/ServerSideSample/ServerSideSample.csproj

Fixes #399 and follows up on fixing a missing generated resource from #372 since that file was either omitted from commit or manually edited.
This PR attempts to target both net5.0-rc1 packages and netcore3.1.x packages

Target net5.0 and netstandard2.x and set either EditForm's Model or EditContext 

---

src/BlazorStrap/wwwroot/blazorStrap.js

#423 Wrap the contents of `collapsingElementEnd` in `if (element) {}` so that if the element already has been destroyed in the DOM, an error will not occur.

Fix for #423

---

src/BlazorStrap/Components/Dropdown/BSDropdownItem.razor.cs

Observed null reference when the dropdown menu was used without the BSDropdown.
```
<BSNav IsList="true" IsNavbar="true">
<BSNavItem IsDropdown="true" @bind-IsOpen="@isFeature1MenuOpen
<BSDropdownToggle IsLink="true" @onclick="OnClickFeature1" Class="text-white">Feature1<BSDropdownToggle>
<BSDropdownMenu @bind-IsOpen="@isFeature1MenuOpen">
<BSDropdownItem Href="item1" @onclick="OnClickFeature1">Item1</BSDropdownItem>
..
</BSDropdownMenu>
</BSNavItem>
</BSNav>
```

Fix null reference when dropdown menu is used with  BSNav / BSNavItem

---

src/SampleCore/wwwroot/snippets/themes/themes1.html
src/SampleCore/wwwroot/snippets/themes/themes2.html
src/SampleCore/wwwroot/snippets/themes/themes3.html
src/SampleCore/wwwroot/snippets/themes/themes4.html
src/SampleCore/wwwroot/snippets/themes/themes5.html

Currently the step-by-step for Themes provides the 'Css' version however the code samples then go on to use the 'CSS' version.
This change will make them consistent (and my impression is the 'Css' version is considered more proper now)

Update code samples for Themes docs

---

src/BlazorStrap/Components/Carousel/BSCarousel.razor.cs
src/BlazorStrap/Components/Carousel/BSCarouselControl.razor.cs
src/BlazorStrap/Components/Carousel/BSCarouselIndicatorItem.razor.cs
src/BlazorStrap/Components/Carousel/BSCarouselIndicators.razor
src/BlazorStrap/Components/Carousel/BSCarouselIndicators.razor.cs
src/BlazorStrap/Components/Carousel/BSCarouselItem.razor.cs
src/SampleCore/Pages/Carousels.razor
src/SampleCore/wwwroot/snippets/carousels/carousels1.html
src/SampleCore/wwwroot/snippets/carousels/carousels2.html
src/SampleCore/wwwroot/snippets/carousels/carousels3.html
src/SampleCore/wwwroot/snippets/carousels/carousels4.html
src/SampleCore/wwwroot/snippets/carousels/carousels5.html

Hello!
Lots of updates for the carousel component here. This was all spawned by an exception caused when the parent of a carousel component re-rendered while the carousel was in the middle of an animation. I found this by subscribing to the ActiveIndexChanged event on the BSCarouselControl. You can replicate this on any of your sample carousels by subscribing as so:
```csharp
<BSCarouselControl CarouselDirection="CarouselDirection.Previous" ActiveIndexChanged="@indexChanged" />
```
This leads to errors in both server and client side cases. Here is a shot of the server side error:
Several things happened in this case:
1. Clicking on the BSCarouselControl element fires the slide transition code and then immediately fires the ActiveIndexChanged event.
2. The parent, seeing that an event has …

Carousel updates

---

src/BlazorStrap/Components/Carousel/BSCarousel.razor.cs
src/SampleCore/Pages/ModalCarousel.razor

Reordered BSCarousel to put lifecycle events before non-lifecycle events.
Created demo with a carousel in a modal for easy testing. Didn't add the demo to the nav so you have to manaually navigate to "/modalcarousel".
Added additional timer which runs when the animations should start. If, after 2 seconds, the animations have not finished (due most likely to a hidden carousel OR the RDP + FF issue #383 ) then it will manually finish the animation.
Theoretically the timer could be closer to 0.6 sec (the transition duration specified in bootstrap) but I wanted to give some cushion.
Risk: If someone has overridden the bootstrap $carousel-transition-duration scsss variable to be longer than 2 sec then this will effectively snap-finish the animation after 2 seconds have elapsed. I don't think …

Carousel hidden fix

---

src/BlazorStrap/Components/Carousel/BSCarouselItem.razor
src/SampleCore/Pages/Carousels.razor

This change allows developers to only supply child content and not supply a value for src when using the BSCarouselItem class. Previously, if no value was supplied for the image source, a missing image was displayed. Or, alternatively, formatting problems with child content arose when using a 1x1 transparent gif to "trick" the carousel component into not displaying.
Instead of seeing something like this: [https://ibb.co/PNwgb5p](https://ibb.co/PNwgb5p)
developers can now create complex content with items both above and below the image like this: [https://ibb.co/KXw6V25](https://ibb.co/KXw6V25)
Sample usage where the "item.Source" property values are all set to null in the context object originating with the "MyItems" collection:
`<BSDataCarousel Items="MyItems" Context="item">`
` …

Carousel - BSCarouselItem skips image rendering when no src image is supplied

---

src/BlazorStrap/Components/Forms/BSInput.cs
src/SampleCore/Pages/Forms.razor

Fixed and added support for nullable checkbox!

Fix https://github.com/chanan/BlazorStrap/issues/456

---

src/BlazorStrap/Components/BootstrapComponents/BSModal.razor
src/BlazorStrap/Components/BootstrapComponents/BSModal.razor.cs

Allow set styles for Modal footer and fix empty footer error, that block us to update to latest version of BlazorStrap

Allow set styles for Modal footer and fix empty footer error

---

src/BlazorStrap-Docs/wwwroot/Static/Components/Modal.md
src/BlazorStrap/Components/BootstrapComponents/BSModal.razor
src/BlazorStrap/Components/BootstrapComponents/BSModal.razor.cs

This makes the close button in the modal optional, for cases where you just don't want to have one, or want to do something weirder to it than just adding a class.
(On a side note, shouldn't this be using `BSCloseButton`?)

Allow modal to not have a close button

---

src/BlazorStrap-Docs/Samples/Components/Progress/Progress1.razor
src/BlazorStrap-Docs/Samples/Components/Progress/Progress2.razor
src/BlazorStrap-Docs/wwwroot/Samples/Components/Progress/Progress1.md
src/BlazorStrap-Docs/wwwroot/Samples/Components/Progress/Progress2.md
src/BlazorStrap-Docs/wwwroot/Static/Components/Progress.md
src/BlazorStrap/Components/BootstrapComponents/BSProgressBar.razor
src/BlazorStrap/Components/BootstrapComponents/BSProgressBar.razor.cs

Fixes a bunch of issues with the `BSProgress`/`BSProgressBar`:
* Adds a `Min` parameter.
* Fixes the docs to actually list the parameters.
* Adds an example showing dynamic updating of the progress bar value.
* Fixes bugs so that the example actually works.
* Fixes the width calculation for multiple progress bars (breaking change, see below for justification).
* Removes rounding of the width percentage (all browsers should cope with decimal widths just fine, and rounding may introduce errors).
Previously, updating the `Value` parameter from the containing component did update the `aria-valuenow` to match, but didn't update the actual rendering of the progress bar.  This was because the `Width` property was only ever updated when progress bars are added/removed, not when parameters were …

Fix up progress bars

---

src/BlazorStrap/Components/Forms/BSFeedback.cs

* When `IsTooltip`, the `valid-tooltip` style was being applied when invalid and not when valid.
* If a `ValidMessage` was set, it was completely ignored instead of being displayed when valid.
* If no `InvalidMessage` was set, it was correctly obtaining a message from the validation context, but then re-using the same message on any subsequent invalid state instead of updating to the new validation error.
* For example, a field is given an invalid value and it displays error A that correctly corresponds to that.  Later, the field is given a different invalid value and it still displays error A despite the validation context now reporting error B.
* As a general rule, it is a bad idea for components to ever write to their `[Parameter]` properties.  This is called out in the official Blazor …

Fixes for BSFeedback

---

src/BlazorStrap/Components/BootstrapComponents/BSDropdownItem.razor
src/BlazorStrap/Components/BootstrapComponents/BSListGroupItem.razor
src/BlazorStrap/Components/BootstrapComponents/BSToggle.razor

This adds some missing `type="button"` on `<button>` elements, because the HTML standard decided in its infinite wisdom that clicking buttons inside forms should submit them by default unless you explicitly tell them not to.
If you _really_ want these to be a submit button, you can (in 2/3 cases) re-enable it by overriding the type attribute.  But it's very unlikely that you do.

Don't submit when clicking buttons

---

src/BlazorStrap/Components/BootstrapComponents/BSDropdown.razor.cs
src/BlazorStrap/Components/BootstrapComponents/BSPopover.razor.cs

This successfully works around the problem mentioned in #528, but perhaps does not solve their underlying causes.
For whatever reason it looks like a single click on a BSToggle resulted in two calls to ShowActionsAsync (and the same on hiding), and that consequently two calls to `AddDocumentEventAsync` were made without unregistering in between, which appeared to get the event registration "stuck on" (even though more than two calls to remove it also happened, it was not actually removed).
This change doesn't prevent the multiple calls from happening, but it does ignore the second one.

Ignore duplicate calls to show/hide

---

src/BlazorStrap/Components/BootstrapComponents/BSTooltip.razor.cs

A typo in `BSTooltip` was making it so that after showing and hiding a tooltip, it was not visible but was still intercepting mouse events.
In my case that was making it so that in a grid of icons with tooltips, fewer and fewer would actually work since the `mouseenter` event wasn't reaching the icon; it was being intercepted by the tooltip instead.
(I'm not sure why anyone would put interactive elements into a tooltip anyway, so they shouldn't need pointer events in the first place, but apparently some people do.)
Caveat: I can't really tell in my test environment since I have animations disabled, but this does seem like perhaps this might make the tooltips vanish immediately instead of fading out... are they supposed to fade out?

Tooltips wouldn't fully hide

---

src/BlazorStrap/Components/Forms/BSFeedback.cs

This fixes `<BSFeedback>` rendering the `<br/>` literally when there are multiple errors in a single control.

Properly renders multi-line feedback

---

src/BlazorStrap/Utilities/TryParseString.cs

This extends `BSInput`'s parsing further to allow it to parse (almost) any type.
(The previous implementation just reported an empty string error when it encountered an unsupported type, which included `uint`.)
In actual fact, the generic implementation supports all of the other types that are being manually parsed above, so it's likely that they all could be removed and just let that do all the work.  I haven't done that because I haven't checked if there's some quirk of the current parsing that's somehow different from the generic parsing.

Parse any type

---

src/BlazorStrap/Utilities/TryParseString.cs

[I think it's a framework bug](https://github.com/dotnet/aspnetcore/issues/42435) but it turns out that `BindConverter.TryConvertTo` can throw exceptions for certain kinds of parsing failures.  So defend against that.

Exception defence

---

src/BlazorStrap-Docs/wwwroot/Static/V4/Content/Tables.md
src/BlazorStrap-Docs/wwwroot/Static/V5/Content/Tables.md
src/BlazorStrap.V4/Components/Datatable/BSDataTableHead.razor
src/BlazorStrap.V4/Components/Datatable/BSDataTableHead.razor.cs
src/BlazorStrap.V5/Components/Datatable/BSDataTableHead.razor
src/BlazorStrap.V5/Components/Datatable/BSDataTableHead.razor.cs

There was no way to change the size of the column filter input for a `BSDataTableHead`. For a `BSTable` with `IsSmall="true"` the filter input box looked to big.
This PR adds a property `FilterSize` (of type Size) which sets the `InputSize` property of the filter text box.

Add property FilterSize to BSDataTableHead

---

src/BlazorStrap/Shared/Components/Modal/BSModalBase.cs

Use Interlocked.Exchange to set BSModalBase internal _callback to null if it is about to be invoked. This ensures that it is not invoked multiple times when rendering under complex scenarios.
When you ShowAsync the modal within the parent component OnDoRender function (on first render), the Modal is left in a broken state. It is shown, then immediately disappears but the grey backdrom remains.
This bug is present on `master`. Showcased in the following repo (note, please update *.csproj references to point to your local repo of BlazorStrap / BlazorStrap.V5, and ensure the repo is clean / up to date.  https://github.com/m-chandler/blazor-modal-onfirstrender-bug
Component code is also here if you prefer not having to check out a repo etc.
```
<BSModal DataId="modal1" @ref="Modal"> …
```

fix: Fix bug when rendering BSModal in parent component OnDoRender 

---

src/BlazorStrap.V5/Components/Datatable/BSDataTable.razor
src/BlazorStrap/Shared/Components/Datatable/BSDataTableBase.cs

Added Colspan to a TD element, to allow spanning over the entire row, when no data is available ...
```
<BSDataTable Items="Lst" Context="L" PaginationBottom="false" IsStriped="true" IsResponsive="true" NoDataColspan="3">
<Header>
<BSTD>Firstname</BSTD>
<BSTD>Lastname</BSTD>
<BSTD>a number</BSTD>
</Header>
<NoData>
No Data
</NoData>
<Body>
<BSDataTableRow>
<BSTD>@L.FirstName</BSTD>
<BSTD>@L.Lastname</BSTD>
<BSTD>@L.Number.ToString()</BSTD>
</BSDataTableRow>
</Body>
</BSDataTable>
```

Added NoDataColspan in BSDataTableBase

---

src/BlazorStrap/Shared/Components/Common/BSDropdownBase.cs

Fixes #573
I'm not so experienced with the library, but assuming this logic is in here to support forms within dropdowns and prevent them closing when clicking inside the form element. Why not use the parameter <BSDropdown **AllowItemClick**> if this is the required behaviour?

Remove logic to prevent closing dropdown if target is form

---

docs/index.html

This fixes a typo on the docs main page as it was the first thing I saw.

Typo docs index.html

---

src/BlazorStrap/Shared/Components/Common/BSTooltipBase.cs

Only call JavaScriptInterop if control has rendered preventing Exception in Dispose "JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method."

Exception on Dispose

---

src/BlazorStrap/Shared/Components/Common/BSCollapseBase.cs

When `DefaultShown` is `true` BSCollapse can't be hidden

Fixed: When DefaultShown = true, BSCollapse can't be hidden

---

src/BlazorStrap.V4/Components/Forms/BSLabel.razor.cs
src/BlazorStrap.V5/Components/Forms/BSLabel.razor.cs

`ColumMedium` property is not working for `BSLabel`, it only works if `ColumnSmall` is defined, too.

fix issue that column medium is not working for BSLabel

---

src/BlazorStrap/Shared/Components/BSCoreBase.cs

Sometimes an `InvalidOperationException` is thrown when the `TaskCompletionSource` is set multiple times. You can avoid this exception at all if you use `TrySetResult` instead of `SetResult`.
https://github.com/chanan/BlazorStrap/blob/680021f793a9ea83e2c89c68db069321522a4f67/src/BlazorStrap/Shared/Components/BSCoreBase.cs#L88-L93

Avoid exception by using TrySetResult instead of empty catch with SetResult
