chanan/BlazorStrap

src/BlazorStrap/BlazorButton.cshtml
src/BlazorStrap/BlazorInput.cshtml
src/BlazorStrap/BlazorStrap.csproj
src/BlazorStrap/BlazorStrapComponentBase.cs
src/BlazorStrap/CarouselIndicators.cshtml
src/BlazorStrap/ColumnBase.cs
src/BlazorStrap/DynamicElement.cs
src/BlazorStrap/_ViewImports.cshtml
src/BlazorStrap/util/BlazorStrapInterop.cs
src/Sample/App.cshtml
src/Sample/Sample.csproj
src/Sample/Shared/MainLayout.cshtml
src/Sample/Startup.cs
src/Sample/_ViewImports.cshtml
src/Sample/global.json
src/Sample/wwwroot/index.html

Initial Blazor 0.8.0 support
#35

Blazor 0.8.0 support

---

src/BlazorStrap/BlazorInput.cshtml
src/Sample/Pages/forms.cshtml

Fix for value/binding on BlazorInput tag

#34 BlazorInput bind to value

---

src/BlazorStrap/Modal.razor

Modal.IsOpen is now two-way bindable

Modal.IsOpen is now two-way bindable

---

src/BlazorStrap/DynamicElement.cs

Fix to render dynamic elements with `UIEventArgs`
Fixes #49

Fix event args for form submit

---

src/BlazorStrap/Alert.razor
src/BlazorStrap/BlazorNavLink.razor
src/BlazorStrap/Toast.Razor
src/BlazorStrap/util/BlazorStrapInterop.cs
src/Sample/Pages/Index.razor
src/Sample/Pages/Toasts.razor
src/Sample/Shared/NavMenu.razor
src/Sample/wwwroot/css/site.css

i made an attempt to add Toast components in BlazorStrap, Let me know what you think.

I made Toast ¯\_(ツ)_/¯

---

src/BlazorStrap/ListGroupItem.razor

PR for issue https://github.com/chanan/BlazorStrap/issues/53

added conditional button type to ListGroupItem

---

src/BlazorStrap/BlazorButton.razor

This was causing issues trying to do an async callback from a button, I don't think this would cause any other issues.

Change button event from Action to EventCallback

---

src/BlazorStrap/NavItem.razor
src/Sample/Pages/Navbars.razor

Fix for navitem not toggling show when using isdropdown.  This is the expected behavior verified on bootstrap website.

Fix for missing show class on navitem.

---

src/BlazorStrap/BlazorInput.razor
src/BlazorStrap/Carousel.razor
src/BlazorStrap/CarouselControl.razor
src/BlazorStrap/CarouselIndicatorItem.razor
src/BlazorStrap/DropdownItem.razor
src/BlazorStrap/ListGroupItem.razor
src/BlazorStrap/ModalHeader.razor
src/BlazorStrap/NavbarToggler.razor
src/BlazorStrap/Toast.Razor

Replaced most Action and Action<T> with EventCallback and EventCallback<T>
https://github.com/chanan/BlazorStrap/issues/64

Replaced Action<T> with EventCallback<T>

---

src/BlazorStrap/BlazorNav.razor
src/BlazorStrap/DropdownMenu.razor
src/BlazorStrap/DropdownToggle.razor
src/BlazorStrap/NavItem.razor
src/BlazorStrap/util/DropDownManager.cs
src/Sample/Pages/Navbars.razor

This feature controls navbar drop down toggles for the user. The only thing needed is a string Id. You can still use IsOpen and onclick to manually toggle dropdowns if you like.  This will also auto close open drop downs under the same navbar. Much like the java experience. It will not close manual controlled dropdowns  
Please look at the sample for a better description.

Add Drop Down Manager for navbars

---

src/BlazorStrap/BlazorNav.razor
src/BlazorStrap/Dropdown.razor
src/BlazorStrap/DropdownItem.razor
src/BlazorStrap/DropdownMenu.razor
src/BlazorStrap/DropdownToggle.razor
src/BlazorStrap/Modal.razor
src/BlazorStrap/NavItem.razor
src/BlazorStrap/util/DropDownMenuHandler.cs
src/Sample/Pages/Dropdowns.razor
src/Sample/Pages/Navbars.razor

This update removes the requirement for ID. The basic setup is now.
```
<NavItem IsDropdown="true">
<DropdownToggle Color="Color.Light">Dropdown link</DropdownToggle>
<DropdownMenu>
<DropdownItem Href="#">Action</DropdownItem>
</DropdownMenu>
</NavItem>
```
Added Support for Normal Dropdowns and split button.
```
<Dropdown>
<DropdownToggle>Dropdown</DropdownToggle>
<DropdownMenu>
<DropdownItem Href="#">Action</DropdownItem>
<DropdownItem Href="#">Another Action</DropdownItem>
<DropdownItem Href="#">Yet Another Action</DropdownItem>
</DropdownMenu>
</Dropdown>
<Dropdown>
<ButtonGroup>
<BlazorButton Color="Color.Secondary">Action</BlazorButton>
<DropdownToggle IsSplit="true" Color="Color.Secondary" />
<DropdownMenu>
<DropdownItem Href="#">Action</DropdownItem>
<DropdownItem Href="#">Another …
```

DropDownManager changes.

---

src/BlazorStrap/Modal.razor
src/Sample/Pages/Modals.razor

Fixes https://github.com/chanan/BlazorStrap/issues/69
Sample: Fixes multiple modals from showing up when one is closed by clicking on the backdrop

Fix for #69

---

src/BlazorStrap/Collapse.razor
src/BlazorStrap/Dropdown.razor
src/BlazorStrap/DropdownMenu.razor
src/BlazorStrap/DropdownToggle.razor
src/BlazorStrap/Modal.razor
src/BlazorStrap/NavItem.razor
src/BlazorStrap/Popover.razor
src/BlazorStrap/ToggleableComponentBase.cs
src/BlazorStrap/util/DropDownMenuHandler.cs
src/SampleCore/SampleCore.csproj
src/ServerSideSample/Startup.cs

Blocked the ability to use Boolean IsOpen and @ref show/hide/toggle together. Setting bool from a
child is overwritten by the parent. As this is intended functionality by manually controlling IsOpen so these cannot be used together.

Added: Show/Hide/Toggle to Collapse, Dropdowns, Navbar, Popovers.

---

src/BlazorStrap/CarouselItem.razor
src/Sample/wwwroot/snippets/carousels/carousels3.html
src/SampleCore/Pages/Carousels.razor
src/SampleCore/SampleCore.csproj
src/SampleCore/wwwroot/snippets/carousels/carousels3.html
src/ServerSideSample/wwwroot/snippets/carousels/carousels3.html

Added the ability to allow users to click on a carousel image.

Added ActionLink capability to Carousel

---

src/BlazorStrap/BlazorButton.razor
src/BlazorStrap/BlazorNavLink.razor
src/BlazorStrap/DropdownItem.razor

Added Class to BlazorButton and BlazorNavLink. Simplified Class for DropdownItem

---

src/BlazorStrap/BlazorNav.razor
src/BlazorStrap/DropdownToggle.razor
src/BlazorStrap/NavItem.razor
src/BlazorStrap/Util/BlazorNavValues.cs
src/SampleCore/Pages/Samples/Issue97.razor

Enabling Link tag fixes the color issue in Dark navs
Also, I noticed that when the nav was set to IsList, it didn't cascade down to the NavItem - so added IsList to the CascadingValue

Enables Link tag for a dropdown

---

src/BlazorStrap/BlazorStrap.csproj
src/Sample/Sample.csproj
src/SampleCore/SampleCore.csproj

Create PR to update to preview 7.

Updated to preview 7.

---

src/BlazorStrap/Components/Forms/BSForm.razor.cs
src/BlazorStrap/Components/Forms/BSFormFeedback.razor.cs
src/BlazorStrap/Components/Forms/BSInput.razor.cs

Suggestion for optimizing data validation:
* Instead of returning a string from `GetErrorCount` I renamed the function to `HasValidationErrors`.
If at least one validation error occured in the field `true` is returned
* Changed the order in Validation checks (at first properties and variables and after that `HasValidationErrors`.
BTW: Is there any way that my previous pull requests aren't added to a new pull request?

Performance optimizations in Data Validations

---

src/BlazorStrap/BlazorStrap.csproj
src/BlazorStrap/Components/BSCustomizer.razor
src/BlazorStrap/Components/BSCustomizer.razor.cs
src/BlazorStrap/Components/Dropdown/BSDropdown.razor.cs
src/BlazorStrap/Components/Forms/BSInput.razor.cs
src/BlazorStrap/Components/Layout/BSCollapse.razor
src/BlazorStrap/Components/Layout/BSCollapse.razor.cs
src/BlazorStrap/Components/Layout/BSCollapseGroup.razor
src/BlazorStrap/Components/Layout/BSCollapseGroup.razor.cs
src/BlazorStrap/Components/Layout/BSCollapseItem.razor
src/BlazorStrap/Components/Layout/BSCollapseItem.razor.cs
src/BlazorStrap/Components/Layout/BSCollapseToggle.razor
src/BlazorStrap/Components/Layout/BSCollapseToggle.razor.cs
src/BlazorStrap/Components/Layout/BSListItem.razor
src/BlazorStrap/Components/Layout/BSListItem.razor.cs
src/BlazorStrap/Components/Model/BSModal.razor.cs
src/BlazorStrap/Components/Nav/BSNav.razor
src/BlazorStrap/Components/Nav/BSNav.razor.cs
src/BlazorStrap/Components/Nav/BSNavItem.razor.cs
src/BlazorStrap/Components/Nav/BSNavLink.razor.cs
src/BlazorStrap/Components/Nav/BSNavbar.razor.cs
src/BlazorStrap/Components/Tabs/BSTab.razor.cs
src/BlazorStrap/Components/Tabs/BSTabGroup.razor.cs
src/BlazorStrap/Util/Components/ToggleableComponentBase.cs
src/SampleCore/Pages/Index.razor
src/SampleCore/Shared/BootstrapLayout.razor
src/SampleCore/Shared/ThemeSwitcher.razor

Note. BSCustimzer is not complete.

Bug Fixes and New features

---

src/BlazorStrap/Components/Forms/BSButton.razor.cs
src/BlazorStrap/Components/Forms/BSInput.razor.cs
src/BlazorStrap/Components/Forms/BSValidationSummary.cs

+ Adds Support for GUID and Datetime 
+ Adds invalid and isvalid to button as well
+ Adds Support for BSValidationSummory
- The following classes will need to be added to your css.
- **validation-errors**
- **validation-message**
- **validation-success**
Example CSS
.validation-errors li.validation-message { color:red;}
.validation-success li.validation-message { color:green;}

New features

---

src/BlazorStrap/BlazorStrap.csproj
src/BlazorStrap/Components/Forms/BSInput.cs
src/BlazorStrap/Components/Forms/BSValidationSummary.cs
src/BlazorStrap/Components/Layout/BSFormRow.razor
src/BlazorStrap/Components/Layout/BSFormRow.razor.cs
src/BlazorStrap/Components/Nav/BSNavItem.razor.cs

Fixes navbar drop downs. If there are two or more dropdowns. Only the active one may be open

Fix for BSNav dropdowns.

---

src/BlazorStrap/Components/Forms/BSInput.cs
src/SampleCore/Pages/Samples/Issue187.razor

Adds Nullable Int, Long. Double, Guid, DateTime, DateTimeOffset  to BSInput

Adds Nullable support for BSInput

---

src/BlazorStrap/Components/Forms/BSInput.cs

Add support to decimal data type
Add InvariantCulture on conversion double and decimal.

BSInput with decimal number or Nullable (int?/decimal?) - #187

---

src/BlazorStrap/Components/Model/BSModal.razor
src/BlazorStrap/Components/Model/BSModal.razor.cs
src/BlazorStrap/Util/AsyncUtil.cs

- Fixes Issue 198
- Cleans up code in BSModal

Fixes Issue 198.

---

src/BlazorStrap/Components/Forms/BSInput.cs
src/SampleCore/Pages/Samples/Issue187.razor
src/SampleCore/Pages/Samples/Issue206.razor
src/ServerSideSample/Startup.cs

Validation will now only happen on the last field you typed in while filling in a form.

Address Issue 210

---

src/BlazorStrap/Components/Tabs/BSTab.razor.cs
src/SampleCore/Pages/Tabs.razor
src/SampleCore/wwwroot/snippets/tabs/tabs4.html
src/SampleCore/wwwroot/snippets/tabs/tabs5.html

I have been trying to figure out the best way to set the active tab if a user comes from an external link as it seemed that the first tab is currently always chosen.
As Selected is already taken as a property in BSTabBase i added SetSelected just to highlight what i am trying to achieve.
I added two examples to the Tabs page in the sample to show it in action.
Something isn't right as there are a bunch of `system.objectdisposedexception: 'cannot process pending renders after the renderer has been disposed.` exceptions when navigating, but hopefully enough to explain what i am trying to do

Set Active Tab based on Route or Parameter

---

src/BlazorStrap/Components/Tabs/BSTab.razor

Corrects obvious mistake.
Thanks!

Fix default tag name to be list element

---

src/BlazorStrap/wwwroot/blazorStrap.js

- polyfill for String.prototype.includes
- string template literal to string concatenation
Thanks!

:bug: Fix IE11 compatiblity for JS interop. Fixes #237

---

src/BlazorStrap/Components/Forms/BSInput.cs

This commit adds support for Nullable enumerations

Add support for nullable enumeration

---

src/SampleCore/Pages/Modals.razor
src/SampleCore/wwwroot/snippets/modals/modals2.html
src/SampleCore/wwwroot/snippets/modals/modals3.html
src/SampleCore/wwwroot/snippets/modals/modals4.html

Basically, it is about changing `OnClick` to `@onclick` so far.
I haven't done any PR for years, let me know if I messed up something.

#246 - Fix for obsolete Modal examples

---

src/SampleCore/Pages/Index.razor

Small typo fix prominent on home page.

Small typo fix

---

src/SampleCore/Pages/ButtonGroups.razor

Fixes issue #274

---

docs/_content/SampleCore/snippets/themes/themes1.html
docs/_content/SampleCore/snippets/themes/themes2.html
docs/_content/SampleCore/snippets/themes/themes3.html
docs/_content/SampleCore/snippets/themes/themes4.html
docs/_content/SampleCore/snippets/themes/themes5.html
src/SampleCore/Pages/Themes.razor
src/SampleCore/Shared/BootstrapLayout.razor

Documentation update - for IBootstrapCss

Documentation update - for IBootstrapCss

---

src/BlazorStrap/Components/Carousel/BSCarouselItem.razor
src/BlazorStrap/Components/Carousel/BSCarouselItem.razor.cs
src/SampleCore/Pages/Carousels.razor
src/SampleCore/SampleCore.csproj
src/SampleCore/wwwroot/css/demo.css
src/SampleCore/wwwroot/snippets/carousels/carousels4.html

This is a relatively quick addition to the CarouselItem which would allow me to use SVG files (for the purpose of animating them.)
If this is acceptable it will close #289

Added svg capability to CarouselItem

---

src/SampleCore/Pages/Forms.razor
src/SampleCore/wwwroot/snippets/forms/forms10.html

Just fixing a couple of typos in the docs around Radio inputs

Fix typos in documentation

---

src/SampleCore/Pages/CollapsePage.razor
src/SampleCore/wwwroot/snippets/collapse/collapse2.html
src/SampleCore/wwwroot/snippets/collapse/collapse3.html

Show how to use BSCollapseItem and change the accordian syntax to use BSCollapseGroup

Update collapse documentation

---

src/BlazorStrap/Components/Layout/BSCollapseToggle.razor
src/BlazorStrap/Components/Layout/BSCollapseToggle.razor.cs
src/SampleCore/Pages/CollapsePage.razor
src/SampleCore/wwwroot/snippets/collapse/collapse2.html

Pass IsOpen through to BSCollapseToggle ChildContent so that the button contents can change (ie, show/hide)
<BSCollapseToggle Color="Color.Primary">
@(context ? "Hide" : "Show")
</BSCollapseToggle>

Pass IsOpen into BSCollapseToggle ChildContent

---

src/BlazorStrap/Components/BSAlert.razor.cs

Related to #321 but for Alert
Not sure if it's acceptable to use `.ConfigureAwait(true)` in library, but that was the only way I know of how to make this work without additional JS. StateHasChanged did not work if returning after delay on a different thread (which is what `.ConfigureAwait(false)` does)

BSAlert add AutoHide feature

---

src/BlazorStrap/Components/Forms/BSBasicInput.cs
src/BlazorStrap/Components/Forms/BSInput.cs
src/SampleCore/Pages/Forms.razor
src/SampleCore/SampleCore.csproj
src/SampleCore/wwwroot/snippets/forms/forms13.html

I keep needing to focus on inputs (eg, after opening a modal, or showing an input after clicking a button) so I have exposed this via BlazorStrapInterop.
If this is not something you want to support (since it has the JS dependency) could we look at exposing ElementReference so that I could implement the focus on my end?
Cheers

Add ability to Focus on a BSInput or BSBasicInput

---

src/BlazorStrap/Components/Forms/BSFormLabel.razor.cs

Added label sizing.
https://getbootstrap.com/docs/4.4/components/forms/#horizontal-form-label-sizing

Added label sizing.

---

src/SampleCore/Pages/Alerts.razor
src/SampleCore/wwwroot/snippets/alerts/alerts6.html

I did not test this cause not sure how to run it
This PR is for #327

Add documentation for Alert auto-hide feature

---

src/BlazorStrap/Components/Forms/BSButton.razor
src/BlazorStrap/Components/Forms/BSButton.razor.cs
src/BlazorStrap/Components/Pagination/BSPaginationLink.razor
src/BlazorStrap/Components/Pagination/BSPaginationLink.razor.cs
src/SampleCore/Pages/Index.razor
src/SampleCore/Pages/Samples/Issue320.razor

This PR adds parameters for OnClickPreventDefault and OnClickStopPropagation to the BSButton component and the BSPaginationLink component as a fix for #320 .
For example, use the following syntax to stop the default behavior of a BSPaginationLink:
<BSPaginationLink Href="#" PaginationLinkType="PaginationLinkType.NextText" @onclick="onclick" OnClickPreventDefault="true" />

This PR fixes bug #320

---

BlazorStrap.sln

Succesful PR on my fork: https://github.com/SayusiAndo/BlazorStrap/pull/2
Successful merge on my fork: https://github.com/SayusiAndo/BlazorStrap/runs/835062357

BlazorStrapSnippits project path fix

---

src/SampleCore/wwwroot/snippets/carousels/carousels1.html

Added the missing IndexChanged from the prettycode file for the Carousel.

Carousel Help File Updated

---

src/BlazorStrap/Components/Carousel/BSCarousel.razor.cs

Fixes Issue 415

---

src/BlazorStrap/BlazorStrap.csproj
src/BlazorStrap/Components/Model/BSModal.razor.cs
src/BlazorStrap/wwwroot/css/slideout.css
src/Sample/wwwroot/index.html
src/SampleCore/Pages/Modals.razor
src/SampleCore/SampleCore.csproj
src/SampleCore/wwwroot/snippets/modals/modals11.html
src/SampleNetstandard/wwwroot/index.html
src/ServerSideSample/Pages/_Host.cshtml

This adds a new property to the Modal to set up the dialog to slide in from the left.  If the property is set a class is added to the Modal that changes it behaviour.
To aid with this there is a new stylesheet added.
Fixes #442

Adding a the functionality to make a modal slide from the left

---

CONTRIBUTING.md

Simply corrected a misspelling in the contributing.md file.

Minor typo fixed in contributing markdown file.

---

src/BlazorStrap/Components/Carousel/BSCarousel.razor.cs

Add InitializeTimer() and InitializeTransitionTimer() methods to refactor usage of System.Timer.Timer. Remove unused _numberOfItems from BSCarousel.razor.cs and reorganize the file.
This fixes the following System.ObjectDisposedException exception (multiple places):
```
HResult=0x80131622,  Message=Cannot access a disposed object.
Object name: 'Timer'.
Source=System.ComponentModel.TypeConverter
StackTrace:
at System.Timers.Timer.set_Enabled(Boolean value)
at System.Timers.Timer.Start()
at BlazorStrap.BSCarousel.ResetTransitionTimer() in C:\Code_Tmp\Repos\BlazorStrap\src\BlazorStrap\Components\Carousel\BSCarousel.razor.cs:line 148
```
Images associated with this error can be found here:
[Exception Details](https://ibb.co/BnxCBCQ)
[AnimationEnd](https://ibb.co/xYzgSSx) …

BSCarousel.razor.cs - Add InitializeTimer() and InitializeTransitionTimer() methods to refactor usage of System.Timer.Timer

---

src/BlazorStrap-Docs/Samples/Components/Accordion/Accordion4.razor
src/BlazorStrap-Docs/wwwroot/Samples/Components/Accordion/Accordion4.md
src/BlazorStrap-Docs/wwwroot/Static/Components/Accordion.md
src/BlazorStrap/Components/BootstrapComponents/BSAccordionItem.razor.cs

Suggestion to support all accordion items to be collapsed. Respect DefaultShown on first item if value is set to false.

Respect default shown first accordion item

---

BlazorStrap.sln
src/BlazorStrap-Docs/Samples/Content/Tables/Tables2.razor
src/BlazorStrap-Docs/wwwroot/Samples/Content/Tables/Tables2.md
src/BlazorStrap-Docs/wwwroot/Static/Content/Tables.md
src/BlazorStrap/Components/Content/BSDataTable.razor
src/BlazorStrap/Components/Content/BSDataTableRow.razor
src/BlazorStrap/Components/Content/BSDataTableRow.razor.cs

Created an MVP for the general concept of the feature. It can be seen in action in the docs project. Relates to issue #490

Mocked up BSDataTableRow concept

---

src/Extensions/BlazorStrap.Extensions.FluentValidation/FluentValidation.cs

This one I did test (mostly); your code was very similar to some I'd (mostly) written myself to do simple FluentValidation, since I didn't like the behaviour of some of the other libraries around.  But I think there are still some potential improvements.
- `FluentValidatorInjectable` allows you to use injectable non-default constructor parameters, similar to `FluentValidatorInjected`, but without needing to actually register the validator as a service beforehand.
- Example usage: `<FluentValidatorInjectable TValidator="MyDataValidator" />`
- It would probably be nicer if this were just rolled directly into `FluentValidator`, but that would make the injected services parameter required, and I'm not sure if that may have unintended consequences (although it's Blazor, so it ought to be safe …

Some FluentValidation fixes and improvements

---

src/BlazorStrap/Components/Layout/BSRow.razor.cs

Repair guttering

---

src/BlazorStrap/Utilities/TryParseString.cs

This allows `BSInput` to bind to any nullable type; previously it only supported a limited range of types (just nullable ints/bools/etc).  In particular, this now allows it to bind to nullable enums.
Also removed a second unreachable bit of code for parsing enums.

Parse any nullable type

---

src/BlazorStrap/Utilities/TryParseString.cs

You merged a little too quickly. 😁 This simplifies the code of #530 a bit.

Simplify a bit

---

src/BlazorStrap.V4/Components/BSToaster.cs
src/BlazorStrap.V5/Components/BSToaster.cs
src/BlazorStrap/Service/Toaster.cs
src/BlazorStrap/Shared/Components/Common/BSToastBase.cs

Fixes #582
Additionally changes:
* (Toaster)Id from Guid? to Guid
* Remove Eventhandler for Timer.Elapsed in BSToastBase.Dispose (may this will fix the 2nd exception)

Change Children of Toaster to ConcurrentDictionary<Guid, Toasts>

---

src/BlazorStrap-Docs/wwwroot/Static/V4/Forms/Checkbox.md
src/BlazorStrap-Docs/wwwroot/Static/V5/Forms/Checkbox.md
src/BlazorStrap.V4/Components/Forms/BSInputSwitch.razor
src/BlazorStrap.V4/Components/Forms/BSInputSwitch.razor.cs
src/BlazorStrap.V5/Components/Forms/BSInputSwitch.razor
src/BlazorStrap.V5/Components/Forms/BSInputSwitch.razor.cs
src/BlazorStrap/Shared/Components/Forms/BSInputCheckboxBase.cs

Add option to add extra classes to the div container surrounding the input with ContainerClass property.
Will solve #585.

Add container class property to BSInputSwitch
